-- Pings table: one row per location update from a player (hiding/seeking).
-- Run in Supabase SQL Editor. Required for live location pings and God mode map.

CREATE TABLE IF NOT EXISTS public.pings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  player_id bigint NOT NULL,
  game_id uuid NOT NULL,
  lat double precision NOT NULL,
  lng double precision NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pings_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.players (id) ON DELETE CASCADE,
  CONSTRAINT pings_game_id_fkey FOREIGN KEY (game_id) REFERENCES public.games (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS pings_game_created_idx ON public.pings (game_id, created_at DESC);
CREATE INDEX IF NOT EXISTS pings_player_game_idx ON public.pings (player_id, game_id, created_at DESC);

COMMENT ON TABLE public.pings IS 'Location pings from players during hiding/seeking; used for God mode map.';
